In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import tensorflow as tf
import tensorflow.keras.backend as K
import numpy as np
from tensorflow.python.keras import Input, Model, layers

In [2]:
srm=np.loadtxt('rich_model.txt')
srmkernel=np.float32(srm)
srmkernel=np.reshape(srmkernel, [30,1,5, 5 ])
srmkernel=np.transpose(srmkernel, (2, 3, 1,0))

In [3]:
srmkernel.shape

(5, 5, 1, 30)

In [6]:
for k in range(30):
    print('*****')
    print(srmkernel[:,:,0,k])
    print('****')

*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
****
*****
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.

In [57]:
def kernel_init(shape, dtype=None):
    srm=np.loadtxt('../srm/rich_model.txt')
    srmkernel=np.float32(srm)
    srmkernel=np.reshape(srmkernel, [30,1,5, 5 ])
    srmkernel=np.transpose(srmkernel, (2, 3, 1,0))
    
    kernels = np.zeros([5, 5, 3, 30])
    for k in range(30):
        kernels[:,:,0,k] = srmkernel[:,:,0,k]
        kernels[:,:,1,k] = srmkernel[:,:,0,k]
        kernels[:,:,2,k] = srmkernel[:,:,0,k]
    
    assert kernels.shape == shape
    
    return K.variable(kernels, dtype='float32')

In [58]:
def build_model():
    input_tensor = Input(shape=(480,640,3))
    x = layers.Conv2D(30, kernel_size = [5,5],
                      kernel_initializer=kernel_init,
                      strides=2, padding='valid') (input_tensor)
    model = Model(inputs=input_tensor, outputs=x)
    return model

In [59]:
img = plt.imread('1.jpg')
model = build_model()
out = model.predict(np.array([img]))
print(out.shape)

TypeError: variable() got an unexpected keyword argument 'trainable'